highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
# author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Yan Jin's Homepage 
name: Yan Jin 
email: jyfeather@gmail.com 
email_full: mailto:jyfeather@gmail.com
website: blog 
website_full: https://jyfeather.github.io/vitae/
github: jyfeather 
twitter: twitter
google_analytics: UA-46603525-1

# needed for travis-ci build
exclude: [vendor]
