highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
# author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Yan Jin's Homepage 
name: Yan Jin 
email: jyfeather@gmail.com 
email_full: mailto:jyfeather@gmail.com
website: blog 
website_full: https://yanjin.info/
github: jyfeather 
twitter: twitter
tel: +01 425 4991085
tel_full: tel:+014254991085
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 6315 NE Radford Drive, 3421, Seattle, WA 98115 
postcode: 98115
city: Seattle, WA 
country: U.S.A. 
google_analytics: UA-46603525-1

# needed for travis-ci build
exclude: [vendor]
